# Generated by Django 2.1.1 on 2018-09-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('winner', models.CharField(choices=[('Sentinel', 'Sentinel'), ('Scourge', 'Scourge'), ('Draw', 'Draw')], default='Draw', max_length=10)),
                ('cost', models.IntegerField(default=0)),
                ('avg_sentinel', models.IntegerField(default=0)),
                ('avg_scourge', models.IntegerField(default=0)),
                ('count_players_sentinel', models.IntegerField(default=0)),
                ('count_players_scourge', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pts_start', models.IntegerField(default=None)),
                ('pts_dif', models.IntegerField(default=0)),
                ('side', models.CharField(choices=[('Sentinel', 'Sentinel'), ('Scourge', 'Scourge')], default='Sentinel', max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playeringame_set', to='calculator.Game')),
            ],
            options={
                'ordering': ['game', '-side', 'player'],
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-pts', 'nickname']},
        ),
        migrations.AlterField(
            model_name='player',
            name='pts',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playeringame_set', to='calculator.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.GameMode'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='games', through='calculator.PlayerInGame', to='calculator.Player'),
        ),
    ]
