# Generated by Django 2.1.1 on 2018-09-07 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('Sentinel', 'Sentinel'), ('Scourge', 'Scourge')], default='Sentinel', max_length=2)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playeringame_set', to='calculator.Game')),
            ],
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-pts', 'nickname']},
        ),
        migrations.AddField(
            model_name='playeringame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playeringame_set', to='calculator.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.GameMode'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='games', through='calculator.PlayerInGame', to='calculator.Player'),
        ),
    ]
