# Generated by Django 2.1.1 on 2018-09-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20180904_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games', to='calculator.Player'),
        ),
    ]
