# Generated by Django 2.1.1 on 2018-09-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20180907_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playeringame',
            options={'ordering': ['-game', '-side', 'player']},
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[('Sentinel', 'Sentinel'), ('Scourge', 'Scourge'), ('Draw', 'Draw')], default='Draw', max_length=10),
        ),
    ]
