# Generated by Django 2.1.1 on 2018-09-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20180907_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='playeringame',
            name='startPoints',
            field=models.IntegerField(default=0),
        ),
    ]
