# Generated by Django 2.1.1 on 2018-09-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_auto_20180907_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='playeringame',
            options={'ordering': ['game', '-side', 'player']},
        ),
        migrations.AddField(
            model_name='game',
            name='cost',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='difPoints',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='playeringame',
            name='startPoints',
            field=models.IntegerField(default=None),
        ),
    ]
